// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMLT3yRvSSRWYbbilC4m04dm2ix83R98',
    appId: '1:989289023883:web:b78041517ab37db347878e',
    messagingSenderId: '989289023883',
    projectId: 'highpaw-47bd4',
    authDomain: 'highpaw-47bd4.firebaseapp.com',
    storageBucket: 'highpaw-47bd4.appspot.com',
    measurementId: 'G-T3C8SFV8T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHK62G9KT70oqQdFlWJbNDhzxNzce35O8',
    appId: '1:989289023883:android:6743824dcc318fdc47878e',
    messagingSenderId: '989289023883',
    projectId: 'highpaw-47bd4',
    storageBucket: 'highpaw-47bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx2nVQESCoBB7uR4a1ca1FrITl75fRxzs',
    appId: '1:989289023883:ios:7f1ad046fc04509247878e',
    messagingSenderId: '989289023883',
    projectId: 'highpaw-47bd4',
    storageBucket: 'highpaw-47bd4.appspot.com',
    androidClientId:
        '989289023883-bna0kqtcglbdasj941v2063j3t7geeat.apps.googleusercontent.com',
    iosClientId:
        '989289023883-91i2vicnphq1a3pci21jruqmv1htl8fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.highPaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx2nVQESCoBB7uR4a1ca1FrITl75fRxzs',
    appId: '1:989289023883:ios:bd14a1f1c9619e3847878e',
    messagingSenderId: '989289023883',
    projectId: 'highpaw-47bd4',
    storageBucket: 'highpaw-47bd4.appspot.com',
    androidClientId:
        '989289023883-bna0kqtcglbdasj941v2063j3t7geeat.apps.googleusercontent.com',
    iosClientId:
        '989289023883-9h9gr5bpcn8v5i73u1ff5l18eoaj4obp.apps.googleusercontent.com',
    iosBundleId: 'com.example.highPaw.RunnerTests',
  );
}
